//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserRole
    {
        public int urId { get; set; }
        public int urUId { get; set; }
        public int urRId { get; set; }
        public bool urIsDel { get; set; }
        public System.DateTime urAddtime { get; set; }
    
        public virtual Ou_Role Ou_Role { get; set; }
        public virtual Ou_UserInfo Ou_UserInfo { get; set; }
    }
}
