//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserVipPermission
    {
        public int vipId { get; set; }
        public int vipUserId { get; set; }
        public int vipPermission { get; set; }
        public string vipRemark { get; set; }
        public bool vipIsDel { get; set; }
        public System.DateTime vipAddTime { get; set; }
    
        public virtual Ou_Permission Ou_Permission { get; set; }
        public virtual Ou_UserInfo Ou_UserInfo { get; set; }
    }
}
