//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BillFlowNode
    {
        public WF_BillFlowNode()
        {
            this.WF_BillFlowNodeRemark = new HashSet<WF_BillFlowNodeRemark>();
        }
    
        public int BillFlowNodeID { get; set; }
        public Nullable<int> WorkFlowNodeID { get; set; }
        public Nullable<int> NodeStateID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public Nullable<int> BillID { get; set; }
    
        public virtual WF_WorkFlowNode WF_WorkFlowNode { get; set; }
        public virtual WF_NodeState WF_NodeState { get; set; }
        public virtual WF_WorkFlow WF_WorkFlow { get; set; }
        public virtual ICollection<WF_BillFlowNodeRemark> WF_BillFlowNodeRemark { get; set; }
    }
}
