//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BillFlowNodeRemark
    {
        public int BillFlowNodeRemarkID { get; set; }
        public Nullable<int> BillFlowNodeID { get; set; }
        public Nullable<int> TransactorID { get; set; }
        public string Transactor { get; set; }
        public Nullable<System.DateTime> TransactorDate { get; set; }
        public string TransactorOperation { get; set; }
        public string TransactorRemark { get; set; }
    
        public virtual WF_BillFlowNode WF_BillFlowNode { get; set; }
    }
}
