//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BillState
    {
        public WF_BillState()
        {
            this.Bill_Leave = new HashSet<Bill_Leave>();
        }
    
        public int BillStateID { get; set; }
        public string BillStateName { get; set; }
    
        public virtual ICollection<Bill_Leave> Bill_Leave { get; set; }
    }
}
