//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Node
    {
        public WF_Node()
        {
            this.WF_WorkFlowNode = new HashSet<WF_WorkFlowNode>();
        }
    
        public int NodeID { get; set; }
        public string NodeName { get; set; }
    
        public virtual ICollection<WF_WorkFlowNode> WF_WorkFlowNode { get; set; }
    }
}
