//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_NodeState
    {
        public WF_NodeState()
        {
            this.WF_BillFlowNode = new HashSet<WF_BillFlowNode>();
        }
    
        public int NodeStateID { get; set; }
        public string NodeStateName { get; set; }
    
        public virtual ICollection<WF_BillFlowNode> WF_BillFlowNode { get; set; }
    }
}
