//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WorkFlow
    {
        public WF_WorkFlow()
        {
            this.Bill_Leave = new HashSet<Bill_Leave>();
            this.WF_BillFlowNode = new HashSet<WF_BillFlowNode>();
            this.WF_WorkFlowNode = new HashSet<WF_WorkFlowNode>();
        }
    
        public int WorkFlowID { get; set; }
        public string WorkFlowName { get; set; }
    
        public virtual ICollection<Bill_Leave> Bill_Leave { get; set; }
        public virtual ICollection<WF_BillFlowNode> WF_BillFlowNode { get; set; }
        public virtual ICollection<WF_WorkFlowNode> WF_WorkFlowNode { get; set; }
    }
}
